# .air.toml

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe  ./main.go"
bin = "./tmp/main.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "node_modules"]
delay = 1000

[log]
time = true 

[misc]
clean_on_exit = true 